// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package controllers

import (
	"github.com/mllb/sampletodo/models"
	"sync"
)

// Ensure, that TodoServiceMock does implement TodoService.
// If this is not the case, regenerate this file with moq.
var _ TodoService = &TodoServiceMock{}

// TodoServiceMock is a mock implementation of TodoService.
//
//	func TestSomethingThatUsesTodoService(t *testing.T) {
//
//		// make and configure a mocked TodoService
//		mockedTodoService := &TodoServiceMock{
//			CreateTodoFunc: func(title string, body string) error {
//				panic("mock out the CreateTodo method")
//			},
//			GetTodoFunc: func(id uint) (models.Todo, error) {
//				panic("mock out the GetTodo method")
//			},
//			GetTodoListFunc: func() ([]models.Todo, error) {
//				panic("mock out the GetTodoList method")
//			},
//			UpdateTodoFunc: func(id uint, title string, body string) error {
//				panic("mock out the UpdateTodo method")
//			},
//		}
//
//		// use mockedTodoService in code that requires TodoService
//		// and then make assertions.
//
//	}
type TodoServiceMock struct {
	// CreateTodoFunc mocks the CreateTodo method.
	CreateTodoFunc func(title string, body string) error

	// GetTodoFunc mocks the GetTodo method.
	GetTodoFunc func(id uint) (models.Todo, error)

	// GetTodoListFunc mocks the GetTodoList method.
	GetTodoListFunc func() ([]models.Todo, error)

	// UpdateTodoFunc mocks the UpdateTodo method.
	UpdateTodoFunc func(id uint, title string, body string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateTodo holds details about calls to the CreateTodo method.
		CreateTodo []struct {
			// Title is the title argument value.
			Title string
			// Body is the body argument value.
			Body string
		}
		// GetTodo holds details about calls to the GetTodo method.
		GetTodo []struct {
			// ID is the id argument value.
			ID uint
		}
		// GetTodoList holds details about calls to the GetTodoList method.
		GetTodoList []struct {
		}
		// UpdateTodo holds details about calls to the UpdateTodo method.
		UpdateTodo []struct {
			// ID is the id argument value.
			ID uint
			// Title is the title argument value.
			Title string
			// Body is the body argument value.
			Body string
		}
	}
	lockCreateTodo  sync.RWMutex
	lockGetTodo     sync.RWMutex
	lockGetTodoList sync.RWMutex
	lockUpdateTodo  sync.RWMutex
}

// CreateTodo calls CreateTodoFunc.
func (mock *TodoServiceMock) CreateTodo(title string, body string) error {
	if mock.CreateTodoFunc == nil {
		panic("TodoServiceMock.CreateTodoFunc: method is nil but TodoService.CreateTodo was just called")
	}
	callInfo := struct {
		Title string
		Body  string
	}{
		Title: title,
		Body:  body,
	}
	mock.lockCreateTodo.Lock()
	mock.calls.CreateTodo = append(mock.calls.CreateTodo, callInfo)
	mock.lockCreateTodo.Unlock()
	return mock.CreateTodoFunc(title, body)
}

// CreateTodoCalls gets all the calls that were made to CreateTodo.
// Check the length with:
//
//	len(mockedTodoService.CreateTodoCalls())
func (mock *TodoServiceMock) CreateTodoCalls() []struct {
	Title string
	Body  string
} {
	var calls []struct {
		Title string
		Body  string
	}
	mock.lockCreateTodo.RLock()
	calls = mock.calls.CreateTodo
	mock.lockCreateTodo.RUnlock()
	return calls
}

// GetTodo calls GetTodoFunc.
func (mock *TodoServiceMock) GetTodo(id uint) (models.Todo, error) {
	if mock.GetTodoFunc == nil {
		panic("TodoServiceMock.GetTodoFunc: method is nil but TodoService.GetTodo was just called")
	}
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockGetTodo.Lock()
	mock.calls.GetTodo = append(mock.calls.GetTodo, callInfo)
	mock.lockGetTodo.Unlock()
	return mock.GetTodoFunc(id)
}

// GetTodoCalls gets all the calls that were made to GetTodo.
// Check the length with:
//
//	len(mockedTodoService.GetTodoCalls())
func (mock *TodoServiceMock) GetTodoCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockGetTodo.RLock()
	calls = mock.calls.GetTodo
	mock.lockGetTodo.RUnlock()
	return calls
}

// GetTodoList calls GetTodoListFunc.
func (mock *TodoServiceMock) GetTodoList() ([]models.Todo, error) {
	if mock.GetTodoListFunc == nil {
		panic("TodoServiceMock.GetTodoListFunc: method is nil but TodoService.GetTodoList was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTodoList.Lock()
	mock.calls.GetTodoList = append(mock.calls.GetTodoList, callInfo)
	mock.lockGetTodoList.Unlock()
	return mock.GetTodoListFunc()
}

// GetTodoListCalls gets all the calls that were made to GetTodoList.
// Check the length with:
//
//	len(mockedTodoService.GetTodoListCalls())
func (mock *TodoServiceMock) GetTodoListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTodoList.RLock()
	calls = mock.calls.GetTodoList
	mock.lockGetTodoList.RUnlock()
	return calls
}

// UpdateTodo calls UpdateTodoFunc.
func (mock *TodoServiceMock) UpdateTodo(id uint, title string, body string) error {
	if mock.UpdateTodoFunc == nil {
		panic("TodoServiceMock.UpdateTodoFunc: method is nil but TodoService.UpdateTodo was just called")
	}
	callInfo := struct {
		ID    uint
		Title string
		Body  string
	}{
		ID:    id,
		Title: title,
		Body:  body,
	}
	mock.lockUpdateTodo.Lock()
	mock.calls.UpdateTodo = append(mock.calls.UpdateTodo, callInfo)
	mock.lockUpdateTodo.Unlock()
	return mock.UpdateTodoFunc(id, title, body)
}

// UpdateTodoCalls gets all the calls that were made to UpdateTodo.
// Check the length with:
//
//	len(mockedTodoService.UpdateTodoCalls())
func (mock *TodoServiceMock) UpdateTodoCalls() []struct {
	ID    uint
	Title string
	Body  string
} {
	var calls []struct {
		ID    uint
		Title string
		Body  string
	}
	mock.lockUpdateTodo.RLock()
	calls = mock.calls.UpdateTodo
	mock.lockUpdateTodo.RUnlock()
	return calls
}
